name: Integration tests

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@v1.0.0
    secrets: inherit
