name: Integration tests

on:
  pull_request:

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@v1.0.0
    secrets: inherit
    pre-run-script: microk8s-installation.sh
    provider: lxd
