name: Release charm to a branch in channel edge

on:
  workflow_dispatch:
    secrets:
      CHARMHUB_TOKEN:
        required: true

jobs:
  lib-check:
    name: Check libraries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@1.0.3
        with:
          credentials: ${{ secrets.CHARMHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
  tests:
    name: Run tests
    uses: ./.github/workflows/test.yaml
  publish-gunicorn-image:
    name: Publish gunicorn image to charmhub
    runs-on: ubuntu-latest
<<<<<<< HEAD
    needs: [ tests, integration-tests ]
=======
    needs: tests
>>>>>>> upstream/main
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/publish_oci_resource
        with:
          charm-name: gunicorn-k8s
          resource-name: gunicorn-image
          charmhub-token: ${{ secrets.CHARMHUB_TOKEN }}
  select-branch:
    name: Select target branch
    runs-on: ubuntu-latest
    outputs:
      channel: ${{ steps.extract-branch.outputs.branch }}
    steps:
      - name: Get target branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract-branch
  publish-charm:
    name: Publish charm to latest/edge/${{ needs.select-branch.outputs.branch }}
    runs-on: ubuntu-latest
    needs: [ select-branch, publish-gunicorn-image ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@1.0.3
        with:
          credentials: ${{ secrets.CHARMHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          channel: ${{ needs.select-branch.outputs.branch }}
          upload-image: false
